# Feature extraction

1. Bag of words

In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.DataFrame({'text':['people watch cartoon','cartoon watch cartoon','people write articles','cartoon write articles'],'output':[1,1,0,0]})

In [7]:
df

text  output
0    people watch cartoon       1
1   cartoon watch cartoon       1
2   people write articles       0
3  cartoon write articles       0

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [9]:
bow=cv.fit_transform(df['text'])

In [10]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'cartoon': 1, 'write': 4, 'articles': 0}


In [11]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]


In [12]:
cv.transform(["i watch cartoon and write articles"]).toarray()

array([[1, 1, 0, 1, 1]], dtype=int64)

2. N grams

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))

In [17]:
bow=cv.fit_transform(df['text'])

In [18]:
#vocab
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'cartoon': 1, 'people watch': 5, 'watch cartoon': 8, 'cartoon watch': 2, 'write': 9, 'articles': 0, 'people write': 6, 'write articles': 10, 'cartoon write': 3}


3. Tf-Idf

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [21]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
['articles' 'cartoon' 'people' 'watch' 'write']
